### ISSUE TITLE
Problemi evidenziati durante il colloquio di ricevimento

### ISSUE THREAD

**Issue by johnluke88** [umbertoloria/moovie#7]
Proposte:
* Caso d'uso di eccezione login:
    * visto che il caso d'uso di eccezione è molto piccolo, può essere spostato nelle eccezioni del caso d'uso principale
* Le E-Mail non sono per niente boundary
    * i casi d'uso che partono dalle e-mail devono partire dai boundary a cui queste mail linkano
* Sequence diagram:
    * c'è bisogno di un sequence diagram per i casi d'uso d'eccezione
* Class diagram:
    * nasce nel RAD e fare riferimento ad esso nel SDD solo nello schema generale
Altro da aggiungere?
@umbertoloria @michelantonio-panichella

**Comment by umbertoloria** [comment]
Bisogna inoltre:
* mettere, dopo un'invocazione di controllo, un messaggio di ritorno Sì o No
* sistemare l'UML delle associazioni nel RAD

Altro? @michelantonio-panichella

**Comment by umbertoloria** [comment]
Bisogna anche inserire nel RAD i casi d'uso di visualizzazione.

**Comment by umbertoloria** [comment]
Il RAD v1.0 presenta:

- introduzione Sequence Diagrams per i Casi d'Uso d'Eccezione;
- impostazione linguaggio diagrammi più coerente;
- miglioramenti Class Diagram;
- introduzione casi d'uso "visualizza";
- introduzione casi d'uso del sottosistema "gestione".

A breve ci sarà la Pull Request.

**Comment by umbertoloria** [comment]
Tutte le problematiche sono state risolte. Non resta che chiude questa issue.

Grazie a tutti.
